### PR TITLE
Implemented recursive repeat + Coding Train logo

### PR DESCRIPTION
**Pull request by TheTastefulToastie**
Implemented repeat as per my suggestion during the livestream:

- Define '[' and ']' as tokens.
- Consume tokens sequentially.
- Maintain a stack of token sequences.
- Record all tokens to the top sequence on the stack.
- '[' pushes a new sequence to the top of the stack.
- ']' pops a sequence from the top of the stack (or repeats it).

Repeat is implemented by re-inserting the tokens from the sequence at the top of the stack to the front of the token stream.

### CODE REVIEW

**Comment by TheTastefulToastie** [comment]
circle

**Comment by TheTastefulToastie** [comment]
This has actually been super interesting!
Here's some things I've come up with:

# Radiation symbol


# Shining sun
circle4

# Exploding star
circle5

# Thorny wreath
circle6

**Comment by TheTastefulToastie** [comment]
# Added coding train logo...in Logo

coding-train-logo

**Comment by TheTastefulToastie** [comment]
I don't like my first attempt. It had a high number of string and array operations and had to juggle the data around.
A small amount of Logo with a repeat 1000 would cause a huge amount of array juggling.

I changed to a better approach.
No regular expressions and next-to-no string/array manipulations.
It only iterates over the string 1 character at a time without modifying it.
Repeat is implemented by jumping backwards in the string and continuing traversal.
The stack only contains the starting index of the repeat and how many times to repeat it (just 2 integers, no longer contains an entire copy of the buffer)

It's also much simpler and easier to read and it's way faster. You can write huge repeats and still edit the code in real-time.

**Comment by shiffman** [comment]
Thank you, this was so fun to include in the live stream! ❤️

**Pull request closed without merging**
