### PR TITLE
Added Syntax Highlighting

### PR DESCRIPTION
**Pull request by Melvin-Abraham**
The "editor" till now looks more like a notepad rather than a colorful editor with interesting Syntax Highlight functionality. This commit includes **Syntax Highlighting Support** for the editor.

The idea is basically making the `textarea`'s text color **transparent** while making the commands highlight in the background `div`.

_Before..._

screencapture_4

_After..._

screencapture_3

### CODE REVIEW

**Comment by TheTastefulToastie** [comment]
Just tried it out and this looks so nice 👌 
Although it seems to make dragging the drawing in the canvas and resizing the textarea super slow. On the larger coding train logo drawing I can no-longer scroll or resize at all.

**Comment by Melvin-Abraham** [comment]
@TheTastefulToastie I've addressed the performance issue on the starting of _sketch.js_

**Comment by TheTastefulToastie** [comment]
Ah I see. I'm still hesitant to merge though as the code on master gets deployed to the [Live Web Demo](https://codingtrain.github.io/Logo/) and users of that will be affected and will not see the code comment.

**Comment by TheTastefulToastie** [comment]
Sent a PR on your fork which only updates the syntax highlighting when the code changes.
Performance is then back to normal 😀

**Comment by Melvin-Abraham** [comment]
Sure thing... I'll try my best...

**Comment by TheTastefulToastie** [comment]
@Melvin-Abraham I meant that I opened a pull request on your fork [here](https://github.com/Melvin-Abraham/Logo/pull/2)
didn't mean to ask you to do more work 😆 what you've done looks amazing

**Comment by TheTastefulToastie** [comment]
awesome! thanks for this 🌟

**Pull request merged**
