### PR TITLE
Add circle/arc & dot command

### PR DESCRIPTION
**Pull request by NiclasTheSquirrel**

### CODE REVIEW

**Comment by TheTastefulToastie** [comment]
Thanks for this 👍 
I think however we're supporting the Berkeley Logo specification which doesn't have a `circle` command but it does have an `ARC` command:
```
ARC angle radius

	draws an arc of a circle, with the turtle at the center, with the
	specified radius, starting at the turtle's heading and extending
	clockwise through the specified angle.  The turtle does not move.
```
I would be inclined to use `ARC` instead unless anyone else thinks otherwise?

**Comment by NiclasTheSquirrel** [comment]
Ok, I did this because of the TODO on the issues page. I will be sure to only commit with commands from the Berkeley Logo Specification from now on.

**Comment by NiclasTheSquirrel** [comment]
I have changed it to have both the circle and arc command now.

**Comment by TheTastefulToastie** [comment]
cool, although both are using the `ellipse` function of p5.js
the `ARC` command should draw an arc as opposed to a full circle
you can use the p5.js function `arc(x, y, w, h, start. stop, mode)` for this
since the arguments are `ARC angle radius` you can do this with `arc(turtle.x, turtle.y, radius, radius, turtle.dir, turtle.dir + angle, PIE)`
hope that makes sense :grin:

**Comment by TheTastefulToastie** [comment]
Hi, I cloned your branch and tried the new commands but there are a couple of issues.

Looks like the callback functions for the new commands don't have any arguments specified so it's throwing errors from undefined variables.

If you look at the forward command:
https://github.com/CodingTrain/Logo/blob/51fd30f6fcda27545f69033d205a934f075656b3/commandList.js#L12-L16

The callback function has the argument `value` specified which is being passed the number the user types in the Logo source code.

The arguments were also the wrong way around:
```
ARC angle radius

	draws an arc of a circle, with the turtle at the center, with the
	specified radius, starting at the turtle's heading and extending
	clockwise through the specified angle.  The turtle does not move.

```
`angle` should come first.

It seems to be drawing a cheese-wedge shape like this:
image

What it should do is this:
image
Which I found [here](http://www.alancsmith.co.uk/logo/LogoCommandRef14b.pdf).

We'll need to call `noFill()` before `arc()` so that it only draws the lines and set the mode to `OPEN` [documented here](https://p5js.org/reference/#/p5/arc) so that it only draws the curved bit and not a fully enclosed slice shape.

Hope that makes sense, here are the changes I meant:
```Javascript
commandLookUp.add(
  new Command("arc", [new CommandArg("angle", ARGUMENT_TYPES.EXPRESSION), new CommandArg("radius", ARGUMENT_TYPES.EXPRESSION)], (angle, radius) => {
    noFill();
    arc(turtle.x, turtle.y, radius * 2, radius * 2, turtle.dir, turtle.dir + angle, OPEN);
  })
);

commandLookUp.add(
  new Command("circle", [new CommandArg("radius", ARGUMENT_TYPES.EXPRESSION)], radius => {
    ellipseMode(CENTER);
    ellipse(turtle.x, turtle.y, radius * 2, radius * 2);
  })
);

commandLookUp.add(
  new Command("dot", [new CommandArg("radius", ARGUMENT_TYPES.EXPRESSSION)], radius => {
    ellipseMode(CENTER);
    ellipse(turtle.x, turtle.y, radius * 2, radius * 2);
  })
);
```

also best wishes for the new year! :champagne:

**Pull request closed without merging**
