### PR TITLE
Fix all the broken things [Issue #54]

### PR DESCRIPTION
**Pull request by TheTastefulToastie**
Man! This was so spaghetti'd I'm now Italian...

These were the issues:

- Someone removed a break from the switch statement in the constructor of CommandExecutor which meant that float values were pushed to the argument list twice (once as a float and then again as a command).

- In Parser.parse() someone moved the call to nextToken() out of the else condition so that it is always executed.
  The intended functionality is to call parseExpression() when the argument type is int or float.
  After this change nextToken() was always executed regardless, then parseExpression was executed as well if the expression was an int or float, causing arguments to get skipped resulting in attempts to invoke numbers as if they were commands.

- COMMAND_TYPES was renamed to ARGUMENT_TYPES but not everywhere causing ReferenceErrors

- #30 Removed calls to parseInt() and parseFloat() in the CommandExecutor constructor because an argument may be an Expression object. #52 Added them back causing Expression objects to become NaN

- Missing brace at end of parser.js

- #52 also removed the calls to drawingBounds.reset() and drawingBounds.move(turtle.x, turtle.y) which obviously broke the autofit-drawing-to-canvas feature

- The autofit-drawing-to-canvas feature was also broken because someone removed the call to the scaleToFitBoundingBox function ¯\\\_(ツ)\_/¯

- The commandList.js script tag got removed

### CODE REVIEW

**Comment by TheTastefulToastie** [comment]
#54

**Comment by shiffman** [comment]
This is heroic! And I created merge conflicts by merging #55 first. . mind taking one last look?

**Comment by TheTastefulToastie** [comment]
done 🌈

**Comment by TheTastefulToastie** [comment]
@shiffman working now 🎺

**Comment by shiffman** [comment]
Yay! Going to go ahead and merge and we can fix anything else after.

**Pull request merged**
