### PR TITLE
highlight Errros and stop executing bad commands and arguments 

### PR DESCRIPTION
**Pull request by AmrBarghouthi**
when a command that does not exist in the command list or a bad argument is passed the parser throws an exception with the start and end index of error in the editor string 
the exception is caught in the sketch.js 
[try it here](https://amrbarghouthi.github.io/Logo/)

### CODE REVIEW

**Comment by TheTastefulToastie** [comment]
This is really nice!

It doesn't seem to handle recursion though, the error bubbles to the top of the stack and it highlights an entire section as invalid.

image

In the screenshot only the argument for the 'rt' command at the end is invalid, but the whole repeat block gets highlighted.

**Comment by AmrBarghouthi** [comment]
@TheTastefulToastie yah am still thinking of how to handle it neatly

**Comment by AmrBarghouthi** [comment]
@TheTastefulToastie i sovled it in a spaghetti why but it worked

**Comment by TheTastefulToastie** [comment]
haha 👌 

just a heads up, line 109 of parser.js has a bitwise & instead of logical &&
is that intentional?

**Comment by AmrBarghouthi** [comment]
@TheTastefulToastie 🤦‍♂️ my bad
I have a bug for large text scrolling resizing is not handled correctly, do you have any idea how to handle it
perhaps this might help
https://codepen.io/lonekorean/pen/gaLEMR

**Comment by TheTastefulToastie** [comment]
oh yeah I see what you mean
I reckon the textarea and the overlay should both be inside a container.
then set the container to be
```css
grid-area: editor;
overflow: none;
```
then the container will need resizing when dragging the `#resize-handle` instead of the textarea in the `updateEditorSize` function

**Comment by TheTastefulToastie** [comment]
@AmrBarghouthi got it working 😁 
opened a pull request on your branch

**Comment by AmrBarghouthi** [comment]
@TheTastefulToastie thank you I was getting frustrated, I am a hardware guy UI is the moon to me

**Comment by TheTastefulToastie** [comment]
😂

**Pull request merged**
