### PR TITLE
Improved parser with more OOP and new examples

### PR DESCRIPTION
**Pull request by EyLuismi**
Hi! So, as my first public Open Source contribution I wanted to improve the way to handle comands in the parser. I have used more OOP, and now its easier to add new commands.

A command, can expect X number of arguments of the type it wants. Also, everything inside brackets is treated as something you can later process, for example I have added one which expect 3 arguments, and it prints the author in the console log.

I have added the color one because is an easy example which can give more game.

### CODE REVIEW

**Comment by EyLuismi** [comment]
When I created the Merge, I cleaned the conflicts and erased by error "setxy" so I have added it now.
Sorry :S

**Comment by shiffman** [comment]
Awesome, this is super interesting! I'm happy to merge but looks like there are conflicts, apologies for that, can you check?

**Comment by EyLuismi** [comment]
Hi! @shiffman The conflicts has been resolved and I have added of course the new introduced commands to the new system 👍

**Comment by shiffman** [comment]
Great!

**Pull request merged**
