### PR TITLE
Testing args OOP way

### PR DESCRIPTION
**Pull request by AmrBarghouthi**
inspired form #41 but using OOP
A callback function is added to CommandArg class that takes an argument as string to validate the value also a default validator was added for float and integer arguments

for now I only log the erros but it should alert the user somehow 

also i changed COMMAND_TYPES  to ARGUMENT_TYPES it was confusing 

try a bad argument and see the console [here](https://amrbarghouthi.github.io/Logo/index.html)

### CODE REVIEW

**Comment by shiffman** [comment]
Ack, one more time fixing conflicts? I'll merge this one first this time! Apologies! ❤️

**Comment by AmrBarghouthi** [comment]
parseExpression breaks the logic of The OOP testing
i think Expression should be added as new type of argement with it own validtion callback

baiscly the parseExpression should be move to the execution class 
new argemnt type should be added with it's defualt validition

**Comment by shiffman** [comment]
sure!

**Comment by AmrBarghouthi** [comment]
on it ❤️

**Pull request merged**
