### PR TITLE
Add looping, color and make everything gorgeous looking

### PR DESCRIPTION
**Pull request by fabritsius**

### CODE REVIEW

**Comment by fabritsius** [comment]
I made a lot of changes. Turtle supports color and background changing. The webpage looks pretty and is responsive. The result image can be saved. Everything is documented in the README.

You can [see how it looks](https://github.com/fabritsius/shiffmans-code-editor) (hosted with gh-pages)

**Comment by fabritsius** [comment]
Image Example Result
_Inspired you know by what_

**Comment by fabritsius** [comment]
geometry_flower
_Pretty flower_

**Comment by DelSquared** [comment]
Given you got colour down, I think it would be similar to implement something like `str 2` to change stroke weight. (Haven't seen the code yet because I'm on mobile right now I'll have a look later)

**Comment by fabritsius** [comment]
I thought about it also, but decided not to add stroke weight, at the same time implementation of opacity might be a good idea (I am still thinking about both ideas).

**Comment by fabritsius** [comment]
I like how results look and want to preserve some simplicity.

**Comment by DelSquared** [comment]
Fair enough :)

**Comment by TheTastefulToastie** [comment]
This is great!
Would be nice if it resized with the window though.
I have some huge Logo drawings that don't fit in the canvas or the textarea.

**Comment by fabritsius** [comment]
I will probably add a separate branch in the future (or someone will). For now, I decided to create sort of a local standard 400x400 pixels (was thinking about 500px instead cause of Instagram). My reasoning is that it is easier to share and compare this way. And 400px is big enough for enough of details.

**Comment by fabritsius** [comment]
nested_pyramids
_Tara-taratata-tara_

**Comment by fabritsius** [comment]
strange_eye
_Don't blink_

**Comment by shiffman** [comment]
I would love to include the color and some design improvements from here! Could you submit them as separate pull requests using the new parser stuff from #24? Also, if you could include a link to a demo running the browser, this makes it easier to review (but screenshots are also good!)

**Comment by fabritsius** [comment]
The link is there, at the top, [here it is again](https://fabritsius.github.io/logo-code-editor/))

**Comment by shiffman** [comment]
oh, awesome, this is great! my apologies! Would you like to refactor this with the new code and resubmit? I'm glad to merge these designs.

**Comment by fabritsius** [comment]
Sure, I will try. I have no idea how to sync our repositories now, so I will probably refork your current version again and will try to add my features on top. I hope most of the code will fit. This way it probably is even better, cause I will be able to make a pull-request specifically for your repo, with proper links and stuff (also service worker for GitHub has to be adapted a little bit).

All of that means that these 44 commits can be forgotten and this request closed (sadly I can't resolve conflicts in this case).

**Comment by shiffman** [comment]
Ok, thank you and apologies for not managing this process well! Looking forward to any new pull requests!

**Pull request closed without merging**
